# Generated by Django 4.2.25 on 2025-12-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_age_user_avatar_user_bio_user_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_kk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_kk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_kk', models.TextField(blank=True, null=True)),
                ('country_ru', models.TextField()),
                ('country_en', models.TextField(blank=True, null=True)),
                ('country_kk', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('age_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.ManyToManyField(blank=True, to='accounts.genre')),
                ('tropes', models.ManyToManyField(blank=True, to='accounts.trope')),
            ],
        ),
    ]
